# Generated by Django 5.0.6 on 2024-05-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualidade', models.CharField(max_length=50)),
                ('capacidade', models.CharField(max_length=50)),
                ('custo', models.CharField(max_length=50)),
                ('reputacao', models.CharField(max_length=50)),
                ('suporte', models.CharField(max_length=50)),
            ],
        ),
    ]
