# Generated by Django 5.0.6 on 2024-05-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50)),
                ('data_emissao', models.CharField(max_length=50)),
                ('descricao_produtos', models.CharField(max_length=50)),
                ('dados', models.CharField(max_length=50)),
                ('valores', models.CharField(max_length=50)),
            ],
        ),
    ]
