# Generated by Django 5.0.6 on 2024-05-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=50)),
                ('habilidades', models.CharField(max_length=50)),
                ('responsabilidade', models.CharField(max_length=50)),
                ('adaptabilidade', models.CharField(max_length=50)),
                ('etica', models.CharField(max_length=50)),
            ],
        ),
    ]
