# Generated by Django 5.0.6 on 2024-05-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necessidade', models.CharField(max_length=50)),
                ('comportamento', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=50)),
                ('potencial', models.CharField(max_length=50)),
                ('demografia', models.CharField(max_length=50)),
            ],
        ),
    ]
